#!/usr/bin/env node
/* ============================================================
   Builds the localized site from the English source + i18n JSON.

   Outputs (both gitignored, regenerated on every build):
     1. i18n/strings.js   → window.__I18N_STRINGS = { en, id }
                            (the runtime catalog used by i18n/i18n.js for
                             JS-generated strings + the language toggle)
     2. id/index.html
        id/events.html     → English pages with every [data-i18n] /
                             [data-i18n-attr] node swapped to Bahasa, <html
                             lang="id">, and a self-referencing canonical.

   Why a custom transform instead of a DOM library: the site has no bundler
   and no node_modules (see scripts/gen-env.mjs). This uses only Node built-ins
   and a depth-aware tag matcher so nested same-tag elements (e.g. a <span>
   inside a translated <span>) are handled correctly.

   Shared assets are referenced with root-absolute paths (/style.css,
   /assets/…, /vendor/…) in the source, so the generated /id/ pages need NO
   path rewriting — they resolve identically from "/" and "/id/". Inter-page
   links (events.html, index.html#about) stay relative so navigation keeps
   you within the active locale.

   Run locally:  node scripts/build-i18n.mjs
   On Vercel it runs via vercel.json buildCommand (after gen-env.mjs).
   ============================================================ */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

const ORIGIN = 'https://ubudjungleballers.com';

const PAGES = [
  { src: 'index.html',      out: 'id/index.html',      canonical: ORIGIN + '/id/' },
  { src: 'events.html',     out: 'id/events.html',     canonical: ORIGIN + '/id/events' },
];

// ---- locale catalogs --------------------------------------------------------
const en = JSON.parse(readFileSync(join(ROOT, 'i18n/en.json'), 'utf8'));
const id = JSON.parse(readFileSync(join(ROOT, 'i18n/id.json'), 'utf8'));

function get(obj, path) {
  const parts = String(path).split('.');
  let cur = obj;
  for (const p of parts) {
    if (cur == null) return undefined;
    cur = cur[p];
  }
  return cur;
}

// Warn on any key present in en.json but missing/extra in id.json, so the two
// catalogs can't silently drift apart.
function flatKeys(obj, prefix = '', out = []) {
  for (const k of Object.keys(obj)) {
    const v = obj[k];
    const key = prefix ? prefix + '.' + k : k;
    if (v && typeof v === 'object') flatKeys(v, key, out);
    else out.push(key);
  }
  return out;
}
function checkParity() {
  const ek = new Set(flatKeys(en));
  const ik = new Set(flatKeys(id));
  const missing = [...ek].filter((k) => !ik.has(k));
  const extra = [...ik].filter((k) => !ek.has(k));
  if (missing.length) console.warn(`build-i18n: ${missing.length} key(s) missing from id.json: ${missing.slice(0, 8).join(', ')}${missing.length > 8 ? '…' : ''}`);
  if (extra.length) console.warn(`build-i18n: ${extra.length} key(s) in id.json not in en.json: ${extra.slice(0, 8).join(', ')}${extra.length > 8 ? '…' : ''}`);
}

// ---- 1. runtime catalog -----------------------------------------------------
function writeStrings() {
  const body =
    '// AUTO-GENERATED by scripts/build-i18n.mjs — do not edit, do not commit.\n' +
    '// Source of truth: i18n/en.json + i18n/id.json.\n' +
    'window.__I18N_STRINGS = ' + JSON.stringify({ en, id }) + ';\n';
  writeFileSync(join(ROOT, 'i18n/strings.js'), body);
}

// ---- HTML transform helpers -------------------------------------------------

// Find the index of the close tag that matches the element opening at
// `innerStart` (the char just after the opening tag's ">"). Depth-aware, so
// nested same-name tags don't end the match early.
function findMatchingClose(html, innerStart, tag) {
  const open = '<' + tag;
  const close = '</' + tag;
  let depth = 1;
  let i = innerStart;
  while (i < html.length) {
    const nextOpen = html.indexOf(open, i);
    const nextClose = html.indexOf(close, i);
    if (nextClose === -1) return -1;
    if (nextOpen !== -1 && nextOpen < nextClose) {
      // Confirm it's a real tag start (next char is space, >, or /), not a
      // longer tag name like <section> when looking for <s>.
      const after = html[nextOpen + open.length];
      const tagEnd = html.indexOf('>', nextOpen);
      const selfClose = tagEnd !== -1 && html[tagEnd - 1] === '/';
      if (after === ' ' || after === '>' || after === '/' || after === '\n' || after === '\t') {
        if (!selfClose) depth++;
        i = tagEnd === -1 ? nextOpen + open.length : tagEnd + 1;
      } else {
        i = nextOpen + open.length;
      }
    } else {
      depth--;
      if (depth === 0) return nextClose;
      i = nextClose + close.length;
    }
  }
  return -1;
}

// Replace inner content of every [data-i18n="key"] element with dict[key].
function applyInner(html, dict, missing) {
  const re = /data-i18n="([^"]+)"/g;
  const edits = [];
  let m;
  while ((m = re.exec(html))) {
    const key = m[1];
    const val = get(dict, key);
    if (val == null) { missing.add(key); continue; }
    const dpos = m.index;
    const lt = html.lastIndexOf('<', dpos);
    const tagMatch = /^<([a-zA-Z0-9]+)/.exec(html.slice(lt, dpos));
    if (!tagMatch) continue;
    const tag = tagMatch[1];
    const gt = html.indexOf('>', dpos);
    if (gt === -1) continue;
    const innerStart = gt + 1;
    const closePos = findMatchingClose(html, innerStart, tag);
    if (closePos === -1) continue;
    edits.push({ innerStart, innerEnd: closePos, val: String(val) });
    re.lastIndex = closePos; // don't descend into this element
  }
  // Apply right-to-left so earlier offsets stay valid.
  edits.sort((a, b) => b.innerStart - a.innerStart);
  for (const e of edits) html = html.slice(0, e.innerStart) + e.val + html.slice(e.innerEnd);
  return html;
}

// Replace attributes named in [data-i18n-attr="attr:key;attr2:key2"].
function applyAttrs(html, dict, missing) {
  const re = /data-i18n-attr="([^"]+)"/g;
  const edits = [];
  let m;
  while ((m = re.exec(html))) {
    const spec = m[1];
    const dpos = m.index;
    const lt = html.lastIndexOf('<', dpos);
    const gt = html.indexOf('>', dpos);
    if (lt === -1 || gt === -1) continue;
    let openTag = html.slice(lt, gt + 1);
    for (const pair of spec.split(';')) {
      const [attr, key] = pair.split(':');
      if (!attr || !key) continue;
      const val = get(dict, key.trim());
      if (val == null) { missing.add(key.trim()); continue; }
      const safe = String(val).replace(/"/g, '&quot;');
      const attrRe = new RegExp('(\\s' + attr.trim() + '=")[^"]*(")');
      if (attrRe.test(openTag)) {
        openTag = openTag.replace(attrRe, '$1' + safe + '$2');
      } else {
        openTag = openTag.replace(/>$/, ' ' + attr.trim() + '="' + safe + '">');
      }
    }
    edits.push({ start: lt, end: gt + 1, val: openTag });
    re.lastIndex = gt;
  }
  edits.sort((a, b) => b.start - a.start);
  for (const e of edits) html = html.slice(0, e.start) + e.val + html.slice(e.end);
  return html;
}

function buildIdPage(page) {
  let html = readFileSync(join(ROOT, page.src), 'utf8');
  const missing = new Set();

  html = applyInner(html, id, missing);
  html = applyAttrs(html, id, missing);

  // <html lang="en"> → "id" (first occurrence = the document element)
  html = html.replace(/<html\s+lang="en"/, '<html lang="id"');

  // Self-referencing canonical + og:url for the localized page.
  html = html.replace(/(<link\s+rel="canonical"\s+href=")[^"]*(")/, '$1' + page.canonical + '$2');
  html = html.replace(/(<meta\s+property="og:url"\s+content=")[^"]*(")/, '$1' + page.canonical + '$2');

  if (missing.size) {
    console.warn(`build-i18n: ${page.out} — ${missing.size} key(s) had no id translation (left in English): ${[...missing].slice(0, 8).join(', ')}${missing.size > 8 ? '…' : ''}`);
  }

  mkdirSync(dirname(join(ROOT, page.out)), { recursive: true });
  writeFileSync(join(ROOT, page.out), html);
  return html.length;
}

// ---- run --------------------------------------------------------------------
checkParity();
writeStrings();
let pages = 0;
for (const page of PAGES) {
  try {
    buildIdPage(page);
    pages++;
  } catch (err) {
    console.error(`build-i18n: failed to build ${page.out}:`, err.message);
  }
}
console.log(`build-i18n: wrote i18n/strings.js + ${pages}/${PAGES.length} localized page(s)`);
