#!/usr/bin/env node
/* ============================================================
   Generates env.js (gitignored) from environment variables.

   Why this exists: the site is static with no bundler, so client
   JS can't read a .env file directly. This script reads the keys
   from either real environment variables (Vercel build) or a local
   .env.local file (dev), and writes them into env.js as window.__ENV,
   which events.html loads before tournament.js.

   Run locally after editing .env.local:   node scripts/gen-env.mjs
   On Vercel it runs automatically (see vercel.json buildCommand);
   set the same variables in Project Settings → Environment Variables.

   No secrets are committed: .env.local and env.js are both gitignored.
   ============================================================ */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// The variables exposed to the client. Add new public config keys here.
const KEYS = ['SUPABASE_URL', 'SUPABASE_ANON_KEY'];

function parseDotenv(path) {
  const out = {};
  if (!existsSync(path)) return out;
  for (const raw of readFileSync(path, 'utf8').split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

const fromFile = parseDotenv(join(ROOT, '.env.local'));
const env = {};
for (const key of KEYS) {
  // Real environment (Vercel) wins; fall back to .env.local for local dev.
  env[key] = process.env[key] || fromFile[key] || '';
}

const out =
  '// AUTO-GENERATED by scripts/gen-env.mjs — do not edit, do not commit.\n' +
  'window.__ENV = ' + JSON.stringify(env, null, 2) + ';\n';

writeFileSync(join(ROOT, 'env.js'), out);

const set = KEYS.filter((k) => env[k]).length;
console.log(`gen-env: wrote env.js (${set}/${KEYS.length} keys set)`);
